### ISSUE TITLE
Does the dataset on the website have trajectories for both sides?

### ISSUE THREAD

**Issue by TimerChen** [tencent-ailab/hokoff#2]
In README file, the sampling scripts generate files `n_0.hdf5` and `n_1.hdf5` for both sides of agents.
However, the datasets downloaded from [the official website](https://sites.google.com/view/hok-offline) only contain one file called `all_data.hdf5`. 
Does the file contain the data of the two agents? If so, for a trajectory, how do I find the trajectory corresponding to the enemy agent?

**Comment by cloud-qu** [comment]
The released datasets are derived from the original sampled data and include only the controlled side's information. For simplicity, in hok1v1, we merged the sliced files `x_0/1.hdf5` into a single file, `all_data.hdf5`. We did not provide the transitions of the opponent side, as they are considered part of the environment in our benchmarks. 
As noted, if necessary, you can easily sample new datasets with both sides' trajectories.

**Comment by TimerChen** [comment]
> As noted, if necessary, you can easily sample new datasets with both sides' trajectories.

@cloud-qu Thanks for your explanation! I am trying to re-sample the datasets with both sides.
I read the description of datasets in the paper and appendix, but some details about data sampling seem unclear.
- About the *Multi-Difficulty* datasets, only the levels of opponents are provided. I am wondering what are the specific levels of ego agents. 
- In Table 4 of the paper, does the winning rate of *Multi-Difficulty* refer to the built-in bot as the opponent? Or does it mean that the opponents are different opponents used in the sampling of each data set?
- What is the specific value of all reward items? Is it the same as examples of reward config in [hok_env](https://github.com/tencent-ailab/hok_env)?

**Comment by cloud-qu** [comment]
Thank you for your interest in our work.
1. **The levels of ego agents:** For poor datasets, the levels of ego agents are 1 or 2 levels lower than those of the opponents. For expert datasets, the levels of ego agents are 1 or 2 levels higher than those of the opponents.
2. **Winning rates:** Unless otherwise specified, all winning rates mentioned in the paper refer to those against opponents of the same level as in sampling.
3. **Reward configurations:** We have released the reward configurations. Please refer to [1v1](https://github.com/tencent-ailab/hokoff/blob/main/hok1v1/offline_sample/config.json), [3v3](https://github.com/tencent-ailab/hokoff/blob/main/hok3v3/offline_sample/hero_reward.txt)

**Comment by YOUNG-fnxm** [comment]
Hello, may I ask if you encountered this problem during the sampling process #4 
@TimerChen
